version: 0.2

env:
  variables:
    PACKAGE: "https://github.com/JonyUcles/HelloWorldGoApp"
phases:
  install:
    commands:
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}" 
      # Print all environment variables (handy for AWS CodeBuild logs)
      - env
      # Install golint
      - go get -u golang.org/x/lint/golint

  pre_build:
    commands:
        # Make sure we're in the project directory within our GOPATH
      - cd "/go/src/${PACKAGE}"

      # Fetch all dependencies
      - go get -t ./...

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Check the Go code for common problems with 'go vet'
      - go vet .

      # Run all tests included with our application
      - go test .
  
  build:
    commands:
      # Build our go application
      - go build -o main
  
  