steps:
- name: 'mirror.gcr.io/library/golang'
  args: ['go', 'version']
- name: 'mirror.gcr.io/library/golang'
  args: ['go', 'test']
  dir: 'function/dir/from/repo/root'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'testFunction', '--trigger-http', '--runtime', 'go113', '--entry-point', 'StartApplication']
  dir: 'function/dir/from/repo/root'

